{
 "title": "Quorum Store",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Quorum Store Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NUM_BATCH_PER_BLOCK",
   "type": "timeseries",
   "description": "Histogram for the number of batches per (committed) blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(quorum_store_num_batch_per_block_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUM_TXN_PER_BATCH",
   "type": "timeseries",
   "description": "Histogram for the number of transactions per batch.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(quorum_store_num_txn_per_batch_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created batches since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_created_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATED_EMPTY_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created empty batches since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_created_empty_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELIVERED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created batches since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(quorum_store_delivered_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MISSED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the missed batches when execute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(quorum_store_missed_batch_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POS_COUNT",
   "type": "timeseries",
   "description": "Count of the proof-of-store (PoS) gathered since last restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(quorum_store_PoS_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}